// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS4AeNPx2M_5lQv6WJ6RP85rYSe4Z-J2g',
    appId: '1:853054702494:web:afc4b16f91c10db9a30c8f',
    messagingSenderId: '853054702494',
    projectId: 'docbooking-9ec13',
    authDomain: 'docbooking-9ec13.firebaseapp.com',
    storageBucket: 'docbooking-9ec13.appspot.com',
    measurementId: 'G-D5GZXKMRKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA2yNxEEZ2QKHWnEuUsxOiDH9Yv74ZHko',
    appId: '1:853054702494:android:1e227e21b3f5e6aea30c8f',
    messagingSenderId: '853054702494',
    projectId: 'docbooking-9ec13',
    storageBucket: 'docbooking-9ec13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG7wTqlePvOwOGZ5IhL9YFC2krgYsIoSw',
    appId: '1:853054702494:ios:64689fdb67c90f03a30c8f',
    messagingSenderId: '853054702494',
    projectId: 'docbooking-9ec13',
    storageBucket: 'docbooking-9ec13.appspot.com',
    iosBundleId: 'com.example.qvPatient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG7wTqlePvOwOGZ5IhL9YFC2krgYsIoSw',
    appId: '1:853054702494:ios:60dc65a8e6a7e563a30c8f',
    messagingSenderId: '853054702494',
    projectId: 'docbooking-9ec13',
    storageBucket: 'docbooking-9ec13.appspot.com',
    iosBundleId: 'com.example.qvPatient.RunnerTests',
  );
}
